services:
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: nhom09_mysql
      PMA_USER: root
      PMA_PASSWORD: root123
    networks:
      - nhom09_network
    depends_on:
      - nhom09_mysql

  nhom09_mysql:
    image: mysql:8.0
    container_name: nhom09_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tourbookingdb
    ports:
      - "3306:3306"
    networks:
      - nhom09_network
    volumes:
      - mysql_data:/var/lib/mysql

  nhom09_backend:
    image: nhom09-backend
    container_name: nhom09_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:root123@nhom09_mysql:3306/tourbookingdb
      DB_HOST: nhom09_mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: tourbookingdb
      DB_PORT: 3306
    networks:
      - nhom09_network
    depends_on:
      - nhom09_mysql

  nhom09_frontend:
    image: nhom09-frontend
    container_name: nhom09_frontend
    ports:
      - "3000:3000"
    networks:
      - nhom09_network

networks:
  nhom09_network:
    driver: bridge

volumes:
  mysql_data:
